// songs.ts
export const songs = [
  
  {
    id: 1,
    title: 'Alien ost',
    description: 'Description of Song 2',
    artist: 'Spotify',
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2022/01/08/audio_8a76d1ca5b.mp3',
  },
  {
    id: 2,
    title: 'Sky',
    description: 'Description of Song 1',
    artist: 'Spotify',
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2022/01/08/audio_9bb82558f6.mp3',
  },
  {
    id: 3,
    title: 'Get Some Rest',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/08/30/audio_0bc5137ad4.mp3',
  },
  {
    id: 4,
    title: 'Be With You',
    description: 'Description of Song 2',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/06/15/audio_b8328c7a49.mp3',
  },
  {
    id: 5,
    title: 'Minimalistic Light Ambient',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2024/04/10/audio_a002e4c68e.mp3',
  },
  {
    id: 6,
    title: 'happy edm',
    description: 'Description of Song 2',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/12/09/audio_445787f109.mp3',
  },
  {
    id: 7,
    title: 'Minimalistic Inspiration Design Ambient',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2024/04/10/audio_700ba63d30.mp3',
  },
  {
    id: 8,
    title: 'Minimalistic Design Ambient Background',
    description: 'Description of Song 2',
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/10/05/audio_8544d22db8.mp3',
  },
  {
    id: 9,
    title: 'Hypnotic Hip Hop Beat',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/01/05/audio_297daed87c.mp3',
  },
  {
    id: 10,
    title: 'Cupid / Stylish Upbeat RnB Beat',
    description: 'Description of Song 2',
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/04/30/audio_af76a50d34.mp3',
  },
  {
    id: 11,
    title: 'Subterranean Homesick Alien',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/10/05/audio_8544d22db8.mp3',
  },
  {
    id: 12,
    title: 'Phonk Less',
    description: 'Description of Song 2',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/09/26/audio_0275760908.mp3',
  },
  {
    id: 13,
    title: 'What happen to me',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2024/04/27/audio_5e68a7fb68.mp3',
  },
  {
    id: 14,
    title: 'Whiplash - Audio Tonic',
    description: 'Description of Song 2',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/12/21/audio_60b53d002a.mp3',
  },
  {
    id: 15,
    title: 'HIPHOP Simple beat 2',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/08/04/audio_3aea8c32bf.mp3',
  },
  {
    id: 16,
    title: 'Crash',
    description: 'Description of Song 2',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/12/09/audio_445787f109.mp3',
  },
  {
    id: 17,
    title: 'Happy edm',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/12/09/audio_445787f109.mp3',
  },
  {
    id: 18,
    title: 'Hipnotic Hip Hop Beat',
    description: 'Description of Song 2',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2024/01/09/audio_7355016257.mp3',
  },
  {
    id: 19,
    title: 'Quick Spit',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2024/01/09/audio_7355016257.mp3',
  },
  {
    id: 20,
    title: 'Deep House Arcade',
    description: 'Description of Song 2',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/06/25/audio_ded864e440.mp3',
  },
  {
    id: 21,
    title: 'Glitch',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2022/12/17/audio_e02ae20435.mp3',
  },
  {
    id: 22,
    title: 'Strangers',
    description: 'Cinematic Rythmline',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/06/02/audio_320a2e0f57.mp3',
  },
  {
    id: 23,
    title: 'Ocean Breeze beat by JTWAYNE',
    description: 'Description of Song 1',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2024/05/29/audio_f3a1d24f19.mp3',
  },
  {
    id: 25,
    title: 'Perfection',
    description: 'Description of Song 2',
    artist: "Spotify",
    image: 'assets/Music-Icon.png',
    audioUrl: 'https://cdn.pixabay.com/audio/2023/06/15/audio_b8328c7a49.mp3',
  },
  // Add more songs as needed
];
